#!/usr/bin/env python3
"""
Generate internal state-wide player rankings by advanced metric.

Qualification criteria (strict — min% accuracy is critical):
  - Team must have no more than MAX_MISSING_GAMES games with fake/absent
    player-minute data (total team player-minutes < MIN_PLAYER_MIN threshold).
  - Player must meet minimum minutes and games played thresholds.

Output: internal_data/state_player_rankings_2025_26.json
        (internal use only — not published to leaderboard)

Usage:
    python3 generate_state_player_rankings.py
    python3 generate_state_player_rankings.py --min-mpg 20 --min-gp 12
"""

import argparse
import json
from datetime import datetime
from pathlib import Path

STATS_DIR     = Path("2025-26 Team Statistics")
SCHEDULES_DIR = Path("2025-26 Teams Schedules")
OUTPUT_PATH   = Path("internal_data/state_player_rankings_2025_26.json")

# Qualification thresholds
MIN_CLEAN_GAMES       = 18   # teams must have at least this many clean box scores
MIN_PLAYER_MIN_THRESH = 100  # total team player-minutes below this → "missing/fake" game
DEFAULT_MIN_MPG       = 4.0   # Min% > 10%  (MPG / 40 * 100 > 10)
DEFAULT_MIN_GP        = 10

# Metrics where lower = better (for ranking direction)
LOWER_BETTER = {"tov_pct", "to_rate", "fc_per_40", "ind_drtg"}


def _find_team_key(bs: dict, team_name: str) -> str | None:
    """Find the matching team key in a box score's teams dict."""
    name_lower = team_name.lower()
    for k in bs.get("teams", {}):
        if k.lower() == name_lower:
            return k
    for k in bs.get("teams", {}):
        if name_lower in k.lower() or k.lower() in name_lower:
            return k
    return None


def count_clean_games(team_name: str, conf: str) -> tuple[int, int]:
    """Count clean and bad games for a team.

    A game is 'clean' when the team's players sum to at least MIN_PLAYER_MIN_THRESH
    total minutes (indicating real minute data was recorded).

    Key-mismatch fallback: some box scores (e.g. those generated by Mt. San Jacinto's
    scoring system) store teams under abbreviations like 'MSJC-M', 'COD-M', etc. that
    don't match the team's full name. When name matching fails on a 2-team box score,
    we check the max minutes across both teams — in real games both teams have ~200 min,
    in stub games both have ~10 min, so this reliably classifies the game either way.

    Returns (clean_count, bad_count).
    """
    sched_dir = SCHEDULES_DIR / conf / team_name
    if not sched_dir.exists():
        return 0, 999  # schedule folder missing → exclude

    clean, bad = 0, 0
    for game_dir in sched_dir.iterdir():
        if not game_dir.is_dir():
            continue
        json_files = list(game_dir.glob("*.json"))
        if not json_files:
            bad += 1
            continue
        try:
            bs = json.load(open(json_files[0]))
        except (json.JSONDecodeError, OSError):
            bad += 1
            continue

        team_key = _find_team_key(bs, team_name)
        if not team_key:
            # Key mismatch — fall back to checking max minutes across all teams
            all_teams = bs.get("teams", {})
            if not all_teams:
                bad += 1
                continue
            max_min = max(
                sum(
                    int(p.get("stats", {}).get("MIN", 0))
                    for p in players
                    if not p.get("name", "").startswith("TM")
                )
                for players in all_teams.values()
            )
            if max_min >= MIN_PLAYER_MIN_THRESH:
                clean += 1
            else:
                bad += 1
            continue

        players = bs["teams"][team_key]
        total_min = sum(
            int(p.get("stats", {}).get("MIN", 0))
            for p in players
            if not p.get("name", "").startswith("TM")
        )
        if total_min < MIN_PLAYER_MIN_THRESH:
            bad += 1
        else:
            clean += 1

    return clean, bad


def load_all_qualifying_players(min_mpg: float, min_gp: int) -> list[dict]:
    """Load player data from all teams that pass the qualification filter."""
    qualifying = []
    excluded_teams = []

    for conf_dir in sorted(STATS_DIR.iterdir()):
        if not conf_dir.is_dir():
            continue
        conf = conf_dir.name

        for team_dir in sorted(conf_dir.iterdir()):
            if not team_dir.is_dir():
                continue
            team_name = team_dir.name

            # Check data quality
            clean, bad = count_clean_games(team_name, conf)
            if clean < MIN_CLEAN_GAMES:
                excluded_teams.append((team_name, conf, clean, bad))
                continue

            adv_path = team_dir / "advanced_analytics.json"
            ps_path  = team_dir / "player_stats.json"
            if not adv_path.exists() or not ps_path.exists():
                continue

            try:
                adv = json.load(open(adv_path))
                ps  = json.load(open(ps_path))
            except (json.JSONDecodeError, OSError):
                continue

            # Build player lookup: name → averages
            player_avgs = {p["name"]: p["averages"] for p in ps.get("players", [])}

            for p in adv.get("players", []):
                pname = p["name"]
                avg   = player_avgs.get(pname, {})
                mpg   = avg.get("MIN", 0)
                gp    = avg.get("games", 0)

                if mpg < min_mpg or gp < min_gp:
                    continue

                metrics = {k: v for k, v in p.items() if k != "name"}
                qualifying.append({
                    "name":   pname,
                    "team":   team_name,
                    "conf":   conf,
                    "gp":     gp,
                    "mpg":    round(mpg, 1),
                    "ppg":    round(avg.get("PTS", 0), 1),
                    "metrics": metrics,
                })

    return qualifying, excluded_teams


def build_rankings(players: list[dict]) -> dict:
    """Rank all players in each metric. Returns {metric: [ranked entries]}."""
    if not players:
        return {}

    all_metrics = list(players[0]["metrics"].keys())
    rankings = {}

    for metric in all_metrics:
        lower_better = metric in LOWER_BETTER

        # Only rank players with a non-zero value for this metric
        eligible = [
            p for p in players
            if p["metrics"].get(metric, 0) not in (0.0, None)
        ]
        eligible.sort(
            key=lambda p: p["metrics"][metric],
            reverse=(not lower_better),
        )

        rankings[metric] = [
            {
                "rank":  i + 1,
                "name":  p["name"],
                "team":  p["team"],
                "conf":  p["conf"],
                "value": p["metrics"][metric],
                "mpg":   p["mpg"],
                "gp":    p["gp"],
                "ppg":   p["ppg"],
            }
            for i, p in enumerate(eligible)
        ]

    return rankings


def main():
    parser = argparse.ArgumentParser(description="Generate state player rankings")
    parser.add_argument("--min-mpg", type=float, default=DEFAULT_MIN_MPG,
                        help=f"Minimum minutes per game (default: {DEFAULT_MIN_MPG})")
    parser.add_argument("--min-gp",  type=int,   default=DEFAULT_MIN_GP,
                        help=f"Minimum games played (default: {DEFAULT_MIN_GP})")
    args = parser.parse_args()

    print(f"Loading players (min {args.min_mpg} MPG, min {args.min_gp} GP, "
          f"≥{MIN_CLEAN_GAMES} clean games per team)...")

    players, excluded = load_all_qualifying_players(args.min_mpg, args.min_gp)

    print(f"  Excluded {len(excluded)} teams with <{MIN_CLEAN_GAMES} clean games:")
    for team, conf, clean, bad in sorted(excluded, key=lambda x: x[2]):
        print(f"    {team} ({conf}): {clean} clean, {bad} bad")

    qualifying_teams = sorted(set(p["team"] for p in players))
    print(f"  {len(qualifying_teams)} qualifying teams, {len(players)} qualifying players")

    rankings = build_rankings(players)

    output = {
        "season":    "2025-26",
        "generated": datetime.now().isoformat(),
        "criteria": {
            "min_clean_games":          MIN_CLEAN_GAMES,
            "min_player_min_threshold": MIN_PLAYER_MIN_THRESH,
            "min_mpg":  args.min_mpg,
            "min_gp":   args.min_gp,
            "note": (
                "Teams qualify when they have at least min_clean_games box scores "
                "with total team player-minutes >= min_player_min_threshold. "
                "Bad games (near-zero minutes) contribute negligible contamination "
                "to rate stats but are counted to ensure sample integrity."
            ),
        },
        "qualifying_teams": len(qualifying_teams),
        "qualifying_players": len(players),
        "excluded_teams": [
            {"team": t, "conf": c, "clean_games": cl, "bad_games": b}
            for t, c, cl, b in sorted(excluded, key=lambda x: x[2])
        ],
        "rankings": rankings,
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        json.dump(output, f, indent=2)

    print(f"\nWrote {len(rankings)} metric rankings → {OUTPUT_PATH}")

    # Quick sanity check: print top 5 for ind_ortg
    if "ind_ortg" in rankings:
        print("\nTop 5 — Individual Offensive Rating (state):")
        for r in rankings["ind_ortg"][:5]:
            print(f"  #{r['rank']} {r['name']} ({r['team']}): {r['value']}  "
                  f"[{r['mpg']} MPG, {r['gp']} GP]")
    if "ind_drtg" in rankings:
        print("\nTop 5 — Individual Defensive Rating (lower=better):")
        for r in rankings["ind_drtg"][:5]:
            print(f"  #{r['rank']} {r['name']} ({r['team']}): {r['value']}  "
                  f"[{r['mpg']} MPG, {r['gp']} GP]")
    if "ts_pct" in rankings:
        print("\nTop 5 — True Shooting%:")
        for r in rankings["ts_pct"][:5]:
            print(f"  #{r['rank']} {r['name']} ({r['team']}): {r['value']}%  "
                  f"[{r['mpg']} MPG, {r['gp']} GP]")


if __name__ == "__main__":
    main()
